name: Pull Request

on:
  push:
    branches: master
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches: master
      
jobs:
  cancelPreviousRuns:
    name: Cancel previous runs
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Build and Run tests
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
      timeout-minutes: 10
